### ISSUE TITLE
XML error

### ISSUE THREAD

**Issue by mkstephens** [zerocrates/OaiPmhRepository#23]
I've never been able to get the OAI-PMH Repository plugin to work on my instance of Omeka. I saw there was a new version and just downloaded/installed it and am still getting an error. 

My site is: http://archive.lancasterseminary.edu/oai-pmh-repository/request

The error it is returning is: 
error on line 2 at column 6: XML declaration allowed only at the start of the document

Please advise me on how to fix this. Thank you!

**Comment by zerocrates** [comment]
If you view source on that page, you'll see that there's a blank line at the start of the document.

That's actually probably coming from another plugin, not OaiPmhRepository. If you deactivate all your other plugins, the problem should go away. You can then reactivate them one-by-one to see which one is causing the extra line to show up.

**Comment by mkstephens** [comment]
Thank you for that tip - I didn't know where to begin to try and troubleshoot the issue! I deactivated a troublesome plugin that I didn't get from the Omeka site, and it turns out it was the culprit. The OAI-PMH Validator site shows that everything is checking out, so I'm hoping it is fixed. Thanks!

**Comment by Daniel-KM** [comment]
@mkstephens
If there is an issue with the troublesome plugin, do you open a ticket on its repository?

**Comment by mkstephens** [comment]
I did. The plugin is called VideoStream and it was developed by Indiana University Library. I just put in an issue on their GitHub site.

**Comment by jimsafley** [comment]
The same error is happening for me. I've deactivated all other plugins but the problem remains. Is there another reason for Omeka or the repository plugin to be prepending a blank line?

**Comment by zerocrates** [comment]
This is almost always caused by a plugin. Do you have a blank line on every page as well?

**Comment by jimsafley** [comment]
Yes, there's a blank line on every page (see http://911digitalarchive.org). Could it be the order in which I deactivate the plugins?

**Comment by zerocrates** [comment]
My only other immediate idea is that it could be the theme's custom.php.

**Comment by zerocrates** [comment]
I'm actually going to close this issue since the original problem is fixed.
